### ISSUE TITLE
I get 100% accuracy using  SVM with a linear kernel. I dont know why ....

### ISSUE THREAD

**Issue by leilaicruz** [leilaicruz/machine-learning-for-yeast#5]

**Comment by leilaicruz** [comment]
You can see the code [in here](https://github.com/leilaicruz/machine-learning-for-yeast/blob/dev_Leila/prot_domains2lethality.ipynb) of the implentation of the SVM algorithm to predict whether a protein pair shares a synthetic lethality relationship or not. There are some labelled examples of known  and not synthetic lethals pairs. 
Each protein pair is represented in a long vector  of length 7129 components , which is the list of all unique protein domains found in yeast, from yeastmine.yeastgenome.org. So each feature will be 0 if the ith protein domain is not in any of the protein pair domains, 1 is the ith protein domain is in one of the proteins , and 2 if the ith protein domain is in both of the proteins.

The SVM was used with a linear Kernel of degree 3 , and the test dataset was 30% of the initial dataset (70% was used for the training). 
After some predictions and comparison with the test data , I got a 100% accuracy...(?) and my question is what does that mean?? I think there are some flaws in the method.... 

![image](https://user-images.githubusercontent.com/11459658/79123179-d8dc3580-7d99-11ea-8e6e-83ac3075f401.png)

**Comment by leilaicruz** [comment]
This implementation is inspired by this paper cited in the issue of [feature-engineering](https://github.com/leilaicruz/machine-learning-for-yeast/issues/2#issuecomment-610394780)

**Comment by leilaicruz** [comment]
I think one thing could lead to this is the overspecification of the data, because I have more than 7000 features for 500 pairs of genes . When I reduced the features to 100 , then the accuracy is not anymore 100% , yet still high 94% :

![image](https://user-images.githubusercontent.com/11459658/79208755-c7029d00-7e42-11ea-90e5-6bbfa0423fec.png)

**Comment by Gregory94** [comment]
How did you choose your features? Are you sure they are all independent of each other? Because now it sounds as if you make the algorithm dumber so that it makes mistakes.

**Comment by leilaicruz** [comment]
The features are based on whether domain i , is in protein A or /and protein B , and I collected all unique yeast protein domains from P-fam which are around 7000.  So I guess that every component is indeed independent from each other because whether a portein domain is in protein A or B does not depend on the previous domain or another domain , right? 
In the 2nd case what I did was to reduce the total domain list to the first 100 domains.  Hence now my feature matrix to learn/test from consists of 500 rows and 100 columns .

**Comment by Gregory94** [comment]
Maybe I am missing something, but if you have 100 domains (i.e. features), you have a 100 dimensional problem, right? You typically need many training points for each dimension, so in this case you need thousands of training points. If you use 7000 features this problem only gets much worse (this is called the curse of dimensionality). What I understand is that you use 70% of the 500 protein pairs for training, which would then not be enough.

**Comment by leilaicruz** [comment]
Sorry, my training matrix has dimensions 1000(2x500 for protein pairs that are SL and non SL) x7229 protein domains. This gave me 100% accuracy , and when I reduced the matrix to 1000x100 then gave 94% accuracy. 
What I think is that in the first learning I overspecify each of the cases (SL and nonSL ) , so I give more information than what is actually need it for the algorithm to deliver a decent prediction  (?)
All this , [is in this python notebook😉](https://github.com/leilaicruz/machine-learning-for-yeast/blob/dev_Leila/prot_domains2lethality.ipynb)

About the curse of dimensionality , it make sense but then I do not get why I am getting with those dimensions 100% accuracy.🤔

**Comment by leilaicruz** [comment]
I ran a PCA component analysis before the fit to the model , and I got 7 relevant dimensions... for the 1st case, for the case of 100 components for the features I got 4 after the PCA analysis

**Comment by leilaicruz** [comment]
I will restructured the features based on scalars measurements per protein pair data on protein domains. I am still learning 😜 hahaha so I will keep you informed !  I saw this tutorial that could be very useful for beginners https://code.visualstudio.com/docs/python/data-science-tutorial#_train-and-evaluate-a-model

**Comment by leilaicruz** [comment]
When using the number of zeros, ones and twos of the long vector representing each protein pair , considering 5000 pairs, we get a poor accuracy in the SVM model.  To look directly in the code 👉 , [go here](https://github.com/leilaicruz/machine-learning-for-yeast/blob/dev_Leila/prot_domains2lethality.ipynb)

One criteria for selecting those is that the correlation among these variables was the lowest compared with the rest of the variables:
![image](https://user-images.githubusercontent.com/11459658/79503080-dcd5b500-8030-11ea-8b13-531db9d4c327.png)

After assesing the model, this is the ROC curve:
![image](https://user-images.githubusercontent.com/11459658/79502064-61bfcf00-802f-11ea-83c5-4ba81960b5d0.png)
Though, we can still assess the feature importance given by the PCA analysis : 
``` python 

print(abs( pca.components_ ))
[[0.67580333 0.71126353 0.19337543]
 [0.30973457 0.03597185 0.95014237]
 [0.66884554 0.70200443 0.2446128 ]]
```
**Here, pca.components has shape  ```[n_components, n_features]```. Thus, by looking at the PC0 (First Principal Component) which is the first row: ```[0.67580333 0.71126353 0.19337543]```, we can see that  feature 2 is the most important, for the 2nd row, feature 3 is the most prominent and for the last one again the 2nd feature**  Here the order is :
``` # of zeros, #of ones, # of twos```  So the feature less important to predict our results is ```#of zeros``` . However the rest arent great as well . 

```Note: I have also noticed that this preduction get worse when I increased the dimension of the training set```
